### ISSUE TITLE
Running tipboard on windows locally

### ISSUE THREAD

**Issue by the-maux** [the-maux/tipboard#108]
When running tipboard the following exception happen:
``` python
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  ...
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
```

All depencies seems ok when installing individually, but when installing by 
pip install -r requirements.txt there is an error, cause no OpenSSL

This error is linked to https://github.com/django/channels/issues/1396
Wich is on WIP here: https://bugs.python.org/issue37373 and [here](https://github.com/django/channels/issues/1319)

Like the official channels documentation here, it said:

> While you can run the standard Django runserver without the need for Docker, the channels features we’ll be using in later parts of the tutorial will need Redis to run, and we recommend Docker as the easiest way to do this.

I will make a documentation with best practice on how to use tipboard on windows waiting the fix for Windows by Python.

**Comment by the-maux** [comment]
Documentation is [here](https://github.com/the-maux/tipboard/wiki/Windows-Usage)

**Comment by the-maux** [comment]
Fixed by https://github.com/django/channels/issues/1396 thanks  @carltongibson and upgrade here :)
